INSERT INTO PERSON (NAME, SURNAME) VALUES('Mario', 'Rossi');
INSERT INTO PERSON (NAME, SURNAME) VALUES('Laura', 'Bianchi');
INSERT INTO PERSON (NAME, SURNAME) VALUES('Marco', 'Masini');
INSERT INTO PERSON (NAME, SURNAME) VALUES('Rino', 'Gaetano');